version: "3.8"

services:
  idde-mysql:
    image: mysql:8.1.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: jdbcdb
      MYSQL_USER: jdbcuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"

  idde-backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=data-gen, dev
      - SERVER_PORT=8081
    depends_on:
      - idde-mysql
    ports:
      - "8081:8081"
